### ISSUE TITLE
Allow modularization of DAGs

### ISSUE THREAD

**Issue by dervoeti** [stackabletech/airflow-operator#326]
A customer recently ran into a problem when deploying this example: https://docs.stackable.tech/home/stable/airflow/usage-guide/applying-custom-resources#_dag_code

The example itself worked fine, but in the Python code of the DAG everything is in one file. If a user wants to modularize the code (e.g. put the classes SparkKubernetesOperator and SparkKubernetesSensor into their own files), Python needs to know where to find these modules. By default, Python looks in `$PYTHONPATH`, which we explicitly set to `/stackable/app/log_config` at the moment.
Now our mounted DAG folder looks like this:
```
├── main.py
└── stackable
    ├── __init__.py
    ├── spark_kubernetes_sensor.py
    └── spark_kubernetes_operator.py
```
If we now import the class SparkKubernetesOperator like this (in main.py):
`from stackable.spark_kubernetes_operator import SparkKubernetesOperator`
Airflow will fail to load the DAG, because Python does not know where to find the module "stackable", since the mounted folder is not within `$PYTHONPATH`.

As a workaround, the user could extend the path in main.py before the `import` statement, like this:
```
import sys
sys.path.append("/stackable/app/git/current")
```

This feels a bit hacky though. We will not give the user a way to extend `$PYTHONPATH`, but will at least document the workaround and/or expected settings by way of an example. 

# Acceptance criteria

```[tasklist]
### Tasks
- [x] Document the `PATH` where we expected the user to mount ConfigMap DAG.
- [x] Ensure DAGS installed with git-sync are always in `PYTHONPATH`
- [x] Ensure that the config for Vector output works as intended in both cases above (this includes ensuring the vector shuts down cleanly after tests: if this is not the case then a separate issue should be opened)
- [x] Make sure task logs are persisted and dag failures can be debugged
```

**Comment by adwk67** [comment]
Another workaround we can document is to use pod overrides e.g.
```
    ...
    roleGroups:
      default:
        podOverrides:
          spec:
            containers:
              - name: airflow
                env:
                  - name: PYTHONPATH
                    value: "/stackable/app/log_config:/tmp"
    ...
```
This is a bit messy as it requires the user to know the default location.

**Comment by lfrancke** [comment]
To be refined by: Maxi, Razvan, Andrew, Lars

**Comment by lfrancke** [comment]
Is there documentation for this? If so: Can you link it here please?

**Comment by adwk67** [comment]
There's an example here: https://github.com/stackabletech/airflow-operator/blob/main/docs/modules/airflow/pages/usage-guide/applying-custom-resources.adoc#dag-code

**Comment by lfrancke** [comment]
The rendered version: https://docs.stackable.tech/home/nightly/airflow/usage-guide/applying-custom-resources#_dag_code

This did not make it into 24.3, correct?
